# -*- coding: utf-8 -*-
"""ensemble_abusexlmr_indicbert_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JMdrm5wyzbrecNNzHpYfD45Op2Mtdjtr

**Ensemble: IndicBERT + AbuseXlmr**
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 2. Install Required Libraries"""

!pip install transformers datasets accelerate scikit-learn pandas numpy torch -q

"""## 3. Import Libraries"""

import pandas as pd
import numpy as np
import torch
import os
import re
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)
from datasets import Dataset
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix
)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings('ignore')

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

"""## 4. Set Paths

"""

# Path to pretrained AbuseXlmr model (before fine-tuning)
ABUSEXLMR_PRETRAINED_PATH = '/content/drive/MyDrive/Trained Models/MACD/AbuseXlmr'

# Dataset paths
TRAIN_DATA_PATH = '/content/Train.csv'
TEST_DATA_PATH = '/content/Test.csv'

# Verify paths
print(f"AbuseXlmr pretrained model exists: {os.path.exists(ABUSEXLMR_PRETRAINED_PATH)}")
print(f"Train data exists: {os.path.exists(TRAIN_DATA_PATH)}")
print(f"Test data exists: {os.path.exists(TEST_DATA_PATH)}")

"""## 5. Load and Preprocess Data"""

# Load datasets
train_df = pd.read_csv(TRAIN_DATA_PATH)
test_df = pd.read_csv(TEST_DATA_PATH)

print(f"Train dataset shape: {train_df.shape}")
print(f"Test dataset shape: {test_df.shape}")
print(f"\nClass distribution:")
print(train_df['Class'].value_counts())

"""## 6. Text Preprocessing"""

def preprocess_tamil_text(text):

    text = str(text)
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#(\w+)', r'\1', text)
    text = re.sub(r'\S+@\S+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Apply preprocessing
train_df['Text'] = train_df['Text'].apply(preprocess_tamil_text)
test_df['Text'] = test_df['Text'].apply(preprocess_tamil_text)

"""## 7. Data Splitting and Label Mapping"""

# Create label mapping
label2id = {'Non-Abusive': 0, 'Abusive': 1}
id2label = {0: 'Non-Abusive', 1: 'Abusive'}

# Convert labels to numeric
train_df['label'] = train_df['Class'].map(label2id)

# Split train into train and validation (80-20 split)
train_data, val_data = train_test_split(
    train_df,
    test_size=0.2,
    random_state=42,
    stratify=train_df['label']
)

print(f"Train size: {len(train_data)}")
print(f"Validation size: {len(val_data)}")
print(f"Test size: {len(test_df)}")
print(f"\nClass distribution in training set:")
print(train_data['Class'].value_counts())

"""## 8. Calculate Optimal Max Length"""

# Load tokenizer to analyze text lengths
temp_tokenizer = AutoTokenizer.from_pretrained('xlm-roberta-base')

print("Analyzing text lengths...")
train_df['token_length'] = train_df['Text'].apply(
    lambda x: len(temp_tokenizer.encode(x, add_special_tokens=True))
)

print("\nToken Length Statistics:")
print(train_df['token_length'].describe())

max_length = int(train_df['token_length'].quantile(0.95))
max_length = min(max(max_length, 64), 256)

print(f"\n Optimal max_length selected: {max_length}")
pct_covered = (train_df['token_length'] <= max_length).mean() * 100
print(f"  Percentage of texts fully covered: {pct_covered:.2f}%")

train_df = train_df.drop('token_length', axis=1)
del temp_tokenizer

"""## 9. Set Training Configuration"""

# Learning rate
LEARNING_RATE = 2e-5

# Number of epochs
NUM_EPOCHS = 7

print(f"Training Configuration:")
print(f"  Learning rate: {LEARNING_RATE}")
print(f"  Epochs: {NUM_EPOCHS}")
print(f"  Max length: {max_length}")
print(f"  Batch size: 16")

"""## 10. Define Training and Evaluation Functions"""

def compute_metrics(eval_pred):
    """Compute metrics for evaluation"""
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, predictions, average='binary'
    )
    acc = accuracy_score(labels, predictions)

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

def train_model(model_name, model_checkpoint):
    #Fine-tune a model on the training data

    print(f"\n{'='*70}")
    print(f"FINE-TUNING {model_name.upper()}")
    print(f"{'='*70}\n")

    # Load tokenizer and model
    print(f"Loading tokenizer and model from {model_checkpoint}")
    tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_checkpoint,
        num_labels=2,
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True
    )

    # Tokenization function
    def tokenize_function(examples):
        return tokenizer(
            examples['Text'],
            padding='max_length',
            truncation=True,
            max_length=max_length
        )

    # Convert to HuggingFace datasets
    train_dataset = Dataset.from_pandas(train_data[['Text', 'label']])
    val_dataset = Dataset.from_pandas(val_data[['Text', 'label']])

    # Tokenize datasets
    print("Tokenizing datasets")
    train_dataset = train_dataset.map(tokenize_function, batched=True)
    val_dataset = val_dataset.map(tokenize_function, batched=True)

    # Data collator
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    # Training arguments
    training_args = TrainingArguments(
        output_dir=f'./results/{model_name}',
        num_train_epochs=NUM_EPOCHS,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=32,
        learning_rate=LEARNING_RATE,
        warmup_ratio=0.1,
        weight_decay=0.01,
        max_grad_norm=1.0,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        greater_is_better=True,
        logging_dir=f'./logs/{model_name}',
        logging_steps=50,
        push_to_hub=False,
        report_to="none",
        seed=42,
    )

    # Initialize Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    # Train
    print(f"\nStarting fine-tuning")
    trainer.train()

    # Evaluate
    print(f"\nEvaluating on validation set")
    results = trainer.evaluate()

    print(f"\n{model_name.upper()} - Validation Results:")
    print(f"  Accuracy:  {results['eval_accuracy']:.4f}")
    print(f"  F1 Score:  {results['eval_f1']:.4f}")
    print(f"  Precision: {results['eval_precision']:.4f}")
    print(f"  Recall:    {results['eval_recall']:.4f}")

    return trainer, tokenizer, model, results

"""## 11. Fine-tune IndicBERT"""

indicbert_trainer, indicbert_tokenizer, indicbert_model, indicbert_results = train_model(
    'indicbert',
    'ai4bharat/IndicBERTv2-MLM-only'
)

print("\n IndicBERT fine-tuning complete")

"""## 12. Fine-tune AbuseXlmr"""

abusexlmr_trainer, abusexlmr_tokenizer, abusexlmr_model, abusexlmr_results = train_model(
    'abusexlmr',
    ABUSEXLMR_PRETRAINED_PATH
)

print("\n AbuseXlmr fine-tuning complete")

"""## 13. Get Predictions and Probabilities from Both Models"""

def get_predictions_and_probabilities(trainer, tokenizer, texts):
    """
    Get predictions and probability scores from a trained model
    """
    # Prepare dataset
    dataset = Dataset.from_pandas(pd.DataFrame({'Text': texts}))

    def tokenize_function(examples):
        return tokenizer(
            examples['Text'],
            padding='max_length',
            truncation=True,
            max_length=max_length
        )

    dataset = dataset.map(tokenize_function, batched=True)

    # Get predictions
    predictions_output = trainer.predict(dataset)

    # Get logits and convert to probabilities
    logits = predictions_output.predictions
    probabilities = torch.softmax(torch.tensor(logits), dim=-1).numpy()

    # Get predicted classes
    predictions = np.argmax(logits, axis=-1)

    return predictions, probabilities

print("GENERATING PREDICTIONS FROM BOTH MODELS")

# Validation set
val_texts = val_data['Text'].tolist()
val_labels = val_data['label'].values

indicbert_val_preds, indicbert_val_probs = get_predictions_and_probabilities(
    indicbert_trainer, indicbert_tokenizer, val_texts
)

abusexlmr_val_preds, abusexlmr_val_probs = get_predictions_and_probabilities(
    abusexlmr_trainer, abusexlmr_tokenizer, val_texts
)

# Test set
test_texts = test_df['Text'].tolist()

indicbert_test_preds, indicbert_test_probs = get_predictions_and_probabilities(
    indicbert_trainer, indicbert_tokenizer, test_texts
)

abusexlmr_test_preds, abusexlmr_test_probs = get_predictions_and_probabilities(
    abusexlmr_trainer, abusexlmr_tokenizer, test_texts
)

print("All predictions generated!")

"""## 14. Ensemble Method 1: Hard Voting"""

def hard_voting(pred1, pred2):
    """Simple majority voting"""
    ensemble_preds = []
    for p1, p2 in zip(pred1, pred2):
        if p1 == p2:
            ensemble_preds.append(p1)
        else:
            # Tiebreaker: use first model's prediction
            ensemble_preds.append(p1)
    return np.array(ensemble_preds)

hard_voting_val_preds = hard_voting(indicbert_val_preds, abusexlmr_val_preds)
hard_voting_test_preds = hard_voting(indicbert_test_preds, abusexlmr_test_preds)

# Evaluate
precision, recall, f1, _ = precision_recall_fscore_support(
    val_labels, hard_voting_val_preds, average='binary'
)
acc = accuracy_score(val_labels, hard_voting_val_preds)

hard_voting_metrics = {
    'Model': 'Hard Voting',
    'Accuracy': acc,
    'F1 Score': f1,
    'Precision': precision,
    'Recall': recall
}

print("ENSEMBLE: HARD VOTING")
print(f"Accuracy:  {acc:.4f}")
print(f"F1 Score:  {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")

"""## 15. Ensemble Method 2: Soft Voting"""

def soft_voting(probs1, probs2):
    """Average probability scores"""
    avg_probs = (probs1 + probs2) / 2
    ensemble_preds = np.argmax(avg_probs, axis=-1)
    return ensemble_preds, avg_probs

soft_voting_val_preds, soft_voting_val_probs = soft_voting(
    indicbert_val_probs, abusexlmr_val_probs
)
soft_voting_test_preds, soft_voting_test_probs = soft_voting(
    indicbert_test_probs, abusexlmr_test_probs
)

# Evaluate
precision, recall, f1, _ = precision_recall_fscore_support(
    val_labels, soft_voting_val_preds, average='binary'
)
acc = accuracy_score(val_labels, soft_voting_val_preds)

soft_voting_metrics = {
    'Model': 'Soft Voting',
    'Accuracy': acc,
    'F1 Score': f1,
    'Precision': precision,
    'Recall': recall
}

print("ENSEMBLE: SOFT VOTING (Average Probabilities)")
print(f"Accuracy:  {acc:.4f}")
print(f"F1 Score:  {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")

"""## 16. Ensemble Method 3: Weighted Voting"""

def weighted_voting(probs1, probs2, weight1, weight2):
    """Weighted average based on model performance"""
    total_weight = weight1 + weight2
    w1 = weight1 / total_weight
    w2 = weight2 / total_weight

    weighted_probs = (probs1 * w1) + (probs2 * w2)
    ensemble_preds = np.argmax(weighted_probs, axis=-1)

    return ensemble_preds, weighted_probs

# Use F1 scores as weights
weight_indicbert = indicbert_results['eval_f1']
weight_abusexlmr = abusexlmr_results['eval_f1']

print(f"\nWeights based on F1 scores:")
print(f"  IndicBERT: {weight_indicbert:.4f}")
print(f"  AbuseXlmr: {weight_abusexlmr:.4f}")

weighted_voting_val_preds, weighted_voting_val_probs = weighted_voting(
    indicbert_val_probs, abusexlmr_val_probs,
    weight_indicbert, weight_abusexlmr
)
weighted_voting_test_preds, weighted_voting_test_probs = weighted_voting(
    indicbert_test_probs, abusexlmr_test_probs,
    weight_indicbert, weight_abusexlmr
)

# Evaluate
precision, recall, f1, _ = precision_recall_fscore_support(
    val_labels, weighted_voting_val_preds, average='binary'
)
acc = accuracy_score(val_labels, weighted_voting_val_preds)

weighted_voting_metrics = {
    'Model': 'Weighted Voting',
    'Accuracy': acc,
    'F1 Score': f1,
    'Precision': precision,
    'Recall': recall
}

print("ENSEMBLE: WEIGHTED VOTING")
print(f"Accuracy:  {acc:.4f}")
print(f"F1 Score:  {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")

"""## 17. Ensemble Method 4: Stacking"""

# Prepare features for meta-classifier
X_val_meta = np.hstack([indicbert_val_probs, abusexlmr_val_probs])
X_test_meta = np.hstack([indicbert_test_probs, abusexlmr_test_probs])

# Split validation for meta-classifier training
X_meta_train, X_meta_val, y_meta_train, y_meta_val = train_test_split(
    X_val_meta, val_labels, test_size=0.5, random_state=42, stratify=val_labels
)

# Train Logistic Regression
print("\nTraining Logistic Regression meta-classifier...")
meta_lr = LogisticRegression(random_state=42, max_iter=1000)
meta_lr.fit(X_meta_train, y_meta_train)

stacking_lr_val_preds = meta_lr.predict(X_meta_val)
stacking_lr_test_preds = meta_lr.predict(X_test_meta)

# Evaluate
precision, recall, f1, _ = precision_recall_fscore_support(
    y_meta_val, stacking_lr_val_preds, average='binary'
)
acc = accuracy_score(y_meta_val, stacking_lr_val_preds)

stacking_lr_metrics = {
    'Model': 'Stacking (Logistic Regression)',
    'Accuracy': acc,
    'F1 Score': f1,
    'Precision': precision,
    'Recall': recall
}

print("ENSEMBLE: STACKING (Logistic Regression)")
print(f"Accuracy:  {acc:.4f}")
print(f"F1 Score:  {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")

# Train Random Forest
print("\nTraining Random Forest meta-classifier...")
meta_rf = RandomForestClassifier(n_estimators=100, random_state=42)
meta_rf.fit(X_meta_train, y_meta_train)

stacking_rf_val_preds = meta_rf.predict(X_meta_val)
stacking_rf_test_preds = meta_rf.predict(X_test_meta)

# Evaluate
precision, recall, f1, _ = precision_recall_fscore_support(
    y_meta_val, stacking_rf_val_preds, average='binary'
)
acc = accuracy_score(y_meta_val, stacking_rf_val_preds)

stacking_rf_metrics = {
    'Model': 'Stacking (Random Forest)',
    'Accuracy': acc,
    'F1 Score': f1,
    'Precision': precision,
    'Recall': recall
}

print("ENSEMBLE: STACKING (Random Forest)")
print(f"Accuracy:  {acc:.4f}")
print(f"F1 Score:  {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")

"""## 18. Complete Comparison: Individual Models + All Ensembles"""

# Compile all results
all_results = pd.DataFrame([
    {
        'Model': 'IndicBERT',
        'Accuracy': indicbert_results['eval_accuracy'],
        'F1 Score': indicbert_results['eval_f1'],
        'Precision': indicbert_results['eval_precision'],
        'Recall': indicbert_results['eval_recall']
    },
    {
        'Model': 'AbuseXlmr',
        'Accuracy': abusexlmr_results['eval_accuracy'],
        'F1 Score': abusexlmr_results['eval_f1'],
        'Precision': abusexlmr_results['eval_precision'],
        'Recall': abusexlmr_results['eval_recall']
    },
    hard_voting_metrics,
    soft_voting_metrics,
    weighted_voting_metrics,
    stacking_lr_metrics,
    stacking_rf_metrics
])

all_results = all_results.sort_values('F1 Score', ascending=False)

print("COMPLETE PERFORMANCE COMPARISON")
print(all_results.to_string(index=False))

# Save comparison
all_results.to_csv('complete_ensemble_comparison.csv', index=False)

"""## 19. Save All Test Predictions"""

print("SAVING TEST SET PREDICTIONS")

# Individual models
for model_name, test_preds in [
    ('indicbert', indicbert_test_preds),
    ('abusexlmr', abusexlmr_test_preds)
]:
    predictions_df = test_df.copy()
    predictions_df['predicted_class'] = [id2label[pred] for pred in test_preds]

    filename = f'test_predictions_{model_name}_finetuned.csv'
    predictions_df.to_csv(filename, index=False)


# Ensemble predictions
ensemble_predictions = {
    'hard_voting': hard_voting_test_preds,
    'soft_voting': soft_voting_test_preds,
    'weighted_voting': weighted_voting_test_preds,
    'stacking_logistic_regression': stacking_lr_test_preds,
    'stacking_random_forest': stacking_rf_test_preds
}

for method_name, test_preds in ensemble_predictions.items():
    predictions_df = test_df.copy()
    predictions_df['predicted_class'] = [id2label[pred] for pred in test_preds]

    filename = f'test_predictions_ensemble_{method_name}.csv'
    predictions_df.to_csv(filename, index=False)

print("ALL PREDICTIONS SAVED")