# -*- coding: utf-8 -*-
"""Multilingual models performance comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8BA5isHmofzIH_bmpZHI78swTGjSKb2

# Tamil Hate Speech Classification - All Models
## Training XLM-RoBERTa, MuRIL, mBERT, IndicBERT, and AbuseXlmr

## 1. Mount Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 2. Install Required Libraries"""

!pip install transformers datasets accelerate scikit-learn pandas numpy torch -q

"""## 3. Import Libraries"""

import pandas as pd
import numpy as np
import torch
import os
import re
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)
from datasets import Dataset
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

"""## 4. Set Paths



"""

# Path to AbuseXlmr pretrained model
ABUSEXLMR_MODEL_PATH = '/content/drive/MyDrive/Trained Models/MACD/AbuseXlmr'

# Path to datasets
TRAIN_DATA_PATH = '/content/Train.csv'
TEST_DATA_PATH = '/content/Test.csv'

# Verify AbuseXlmr model path exists
if os.path.exists(ABUSEXLMR_MODEL_PATH):
    print(f"AbuseXlmr model found at: {ABUSEXLMR_MODEL_PATH}")
else:
    print(f"AbuseXlmr model not found at: {ABUSEXLMR_MODEL_PATH}")

"""## 5. Load Datasets"""

# Load train and test datasets
train_df = pd.read_csv(TRAIN_DATA_PATH)
test_df = pd.read_csv(TEST_DATA_PATH)

print(f"Train dataset shape: {train_df.shape}")
print(f"Test dataset shape: {test_df.shape}")
print(f"\nTrain dataset preview:")
print(train_df.head())
print(f"\nClass distribution:")
print(train_df['Class'].value_counts())

"""## 6. Text Preprocessing"""

def preprocess_tamil_text(text):
    """
    Preprocess Tamil text for hate speech classification
    """
    if pd.isna(text):
        return ""

    text = str(text)

    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # Remove mentions (@username)
    text = re.sub(r'@\w+', '', text)

    # Remove hashtags but keep the text
    text = re.sub(r'#(\w+)', r'\1', text)

    # Remove email addresses
    text = re.sub(r'\S+@\S+', '', text)

    # Remove extra whitespaces
    text = re.sub(r'\s+', ' ', text).strip()

    # Remove leading/trailing whitespace
    text = text.strip()

    return text

# Apply preprocessing

train_df['Text'] = train_df['Text'].apply(preprocess_tamil_text)
test_df['Text'] = test_df['Text'].apply(preprocess_tamil_text)

"""## 7. Data Splitting and Label Mapping"""

# Create label mapping
label2id = {'Non-Abusive': 0, 'Abusive': 1}
id2label = {0: 'Non-Abusive', 1: 'Abusive'}

# Convert labels to numeric
train_df['label'] = train_df['Class'].map(label2id)

# Split train into train and validation (80-20 split)
train_data, val_data = train_test_split(
    train_df,
    test_size=0.2,
    random_state=42,
    stratify=train_df['label']
)

print(f"Train size: {len(train_data)}")
print(f"Validation size: {len(val_data)}")
print(f"Test size: {len(test_df)}")
print(f"\nClass distribution in training set:")
print(train_data['Class'].value_counts())

"""## 8. Define Model Configurations"""

# Model configurations
models_config = {
    'xlm-roberta': 'xlm-roberta-base',
    'muril': 'google/muril-base-cased',
    'mbert': 'bert-base-multilingual-cased',
    'indicbert': 'ai4bharat/IndicBERTv2-MLM-only',
    'abusexlmr': ABUSEXLMR_MODEL_PATH
}

"""## 9. Set Learning Rate

"""

LEARNING_RATE = 2e-5

"""## 10. Calculate Optimal Max Length"""

# Load tokenizer to analyze text lengths
temp_tokenizer = AutoTokenizer.from_pretrained('xlm-roberta-base')

# Get token lengths for all texts
train_df['token_length'] = train_df['Text'].apply(
    lambda x: len(temp_tokenizer.encode(x, add_special_tokens=True))
)

# Calculate statistics
print("\nToken Length Statistics:")
print(train_df['token_length'].describe())

# Set max_length to cover 95% of texts
max_length = int(train_df['token_length'].quantile(0.95))

# Cap at 256
max_length = min(max_length, 256)

# Ensure at least 64
max_length = max(max_length, 64)

print(f"\nOptimal max_length selected: {max_length}")

pct_covered = (train_df['token_length'] <= max_length).mean() * 100
print(f"  Percentage of texts fully covered: {pct_covered:.2f}%")

train_df = train_df.drop('token_length', axis=1)

del temp_tokenizer

"""## 11. Define Metrics and Training Function"""

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, predictions, average='binary'
    )
    acc = accuracy_score(labels, predictions)

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

def train_and_evaluate_model(model_name, model_checkpoint):
    print(f"\n{'='*70}")
    print(f"TRAINING {model_name.upper()}")
    print(f"{'='*70}\n")

    # Load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_checkpoint,
        num_labels=2,
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True  # For pretrained models with different labels
    )

    # Tokenization function
    def tokenize_function(examples):
        return tokenizer(
            examples['Text'],
            padding='max_length',
            truncation=True,
            max_length=max_length  # Using calculated optimal length
        )

    # Convert to HuggingFace datasets
    train_dataset = Dataset.from_pandas(train_data[['Text', 'label']])
    val_dataset = Dataset.from_pandas(val_data[['Text', 'label']])

    # Tokenize datasets
    train_dataset = train_dataset.map(tokenize_function, batched=True)
    val_dataset = val_dataset.map(tokenize_function, batched=True)

    # Data collator
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    # Optimized training arguments
    model_training_args = TrainingArguments(
        output_dir=f'./results/{model_name}',

        num_train_epochs=7,

        # Batch sizes
        per_device_train_batch_size=16,
        per_device_eval_batch_size=32,

        # Learning rate with warmup
        learning_rate=LEARNING_RATE,
        warmup_ratio=0.1,

        # Regularization
        weight_decay=0.01,
        max_grad_norm=1.0,

        # Evaluation and saving
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        greater_is_better=True,

        # Logging
        logging_dir=f'./logs/{model_name}',
        logging_steps=50,

        # Other
        push_to_hub=False,
        report_to="none",
        seed=42,
    )

    # Initialize Trainer
    trainer = Trainer(
        model=model,
        args=model_training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    # Train the model
    print(f"\nStarting training...")
    trainer.train()

    # Evaluate on validation set
    print(f"\nEvaluating on validation set...")
    results = trainer.evaluate()

    print(f"\n{model_name.upper()} - Validation Results:")
    print(f"  Accuracy:  {results['eval_accuracy']:.4f}")
    print(f"  F1 Score:  {results['eval_f1']:.4f}")
    print(f"  Precision: {results['eval_precision']:.4f}")
    print(f"  Recall:    {results['eval_recall']:.4f}")

    return trainer, tokenizer, results

"""## 12. Train All Models


"""

# Dictionary to store trained models and results
trained_models = {}
all_results = {}

print("STARTING TRAINING")

# Train each model
for model_name, model_checkpoint in models_config.items():
    try:
        trainer, tokenizer, results = train_and_evaluate_model(model_name, model_checkpoint)
        trained_models[model_name] = {'trainer': trainer, 'tokenizer': tokenizer}
        all_results[model_name] = results
        print(f"\n {model_name} training completed successfully")
    except Exception as e:
        print(f"\n Error training {model_name}: {str(e)}")
        print(f"  Continuing with next model...")
        continue
print("TRAINING COMPLETED")

"""## 13. Compare Model Performance"""

# Create comparison dataframe
comparison_data = []
for model_name, results in all_results.items():
    comparison_data.append({
        'Model': model_name,
        'Accuracy': results['eval_accuracy'],
        'F1 Score': results['eval_f1'],
        'Precision': results['eval_precision'],
        'Recall': results['eval_recall']
    })

comparison_df = pd.DataFrame(comparison_data)
comparison_df = comparison_df.sort_values('F1 Score', ascending=False)

print("MODEL PERFORMANCE COMPARISON")
print(comparison_df.to_string(index=False))

# Save comparison to CSV
comparison_df.to_csv('model_comparison_optimized.csv', index=False)
print("\nModel comparison saved to 'model_comparison_optimized.csv'")

"""## 14. Generate Predictions on Test Set for All Models"""

def generate_predictions(model_name, trainer, tokenizer, test_df):
    """
    Generate predictions for test dataset
    """
    print(f"\nGenerating predictions for {model_name}")

    # Create test dataset
    test_dataset = Dataset.from_pandas(test_df[['Text']])

    # Tokenize
    def tokenize_function(examples):
        return tokenizer(
            examples['Text'],
            padding='max_length',
            truncation=True,
            max_length=max_length
        )

    test_dataset = test_dataset.map(tokenize_function, batched=True)

    # Get predictions
    predictions = trainer.predict(test_dataset)
    pred_labels = np.argmax(predictions.predictions, axis=1)
    pred_classes = [id2label[label] for label in pred_labels]

    # Create predictions dataframe
    predictions_df = test_df.copy()
    predictions_df['predicted_class'] = pred_classes

    return predictions_df

# Generate predictions for all models
print("\n" + "="*70)
print("GENERATING TEST SET PREDICTIONS")
print("="*70)

all_predictions = {}

for model_name, model_data in trained_models.items():
    try:
        predictions_df = generate_predictions(
            model_name,
            model_data['trainer'],
            model_data['tokenizer'],
            test_df
        )
        all_predictions[model_name] = predictions_df

        # Save to CSV
        output_filename = f'test_predictions_{model_name}_optimized.csv'
        predictions_df.to_csv(output_filename, index=False)
        print(f"Predictions saved to '{output_filename}'")

    except Exception as e:
        print(f"Error generating predictions for {model_name}: {str(e)}")
        continue

print("ALL PREDICTIONS GENERATED SUCCESSFULLY")